name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-cypress-container .

    - name: Run Cypress tests
      run: docker run --rm my-cypress-container

    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: cypress/screenshots